services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://145.223.26.174:6501
    container_name: prod-livrariateste
    ports:
      - "6500:6500"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://145.223.26.174:6501
